apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: api-env
    literals:
      - DB_HOST=postgresql-postgresql.platform.svc.cluster.local
      - DB_PORT=5432
      - DB_NAME=appdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_URL=redis://redis-master.platform.svc.cluster.local:6379/0
      - MINIO_ENDPOINT=minio.platform.svc.cluster.local:9000
generatorOptions:
  disableNameSuffixHash: true
