name: CI
on:
  pull_request:
  push:
    branches: [ main, master ]
jobs:
  validate-and-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: python -m pip install --upgrade pip pre-commit

      - name: Run pre-commit on all files
        run: pre-commit run --all-files

      - name: Run demo workflow (PowerShell)
        shell: pwsh
        run: |
          pwsh scripts/run_workflow.ps1
          echo "== Artifacts =="
          ls workflows/hello_world/artifacts
