# Markdown linting configuration for CLI Multi-Rapid
default: true

# Disable line length checking for compatibility with long URLs and tables
MD013: false

# Allow HTML in markdown (for badges and complex formatting)
MD033: false

# Allow duplicate heading names (common in API docs)
MD024: false

# Allow bare URLs (common in technical documentation)
MD034: false