version: '3'
tasks:
  up:
    cmds:
      - echo 'up'
  test:
    cmds:
      - echo 'test'
  lint:
    cmds:
      - echo 'lint'
  build:
    cmds:
      - echo 'build'
  sbom:
    cmds:
      - echo 'sbom'
  release:dry:
    cmds:
      - echo 'release:dry'
