apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DROP_TOKEN
      remoteRef:
        key: /cli-multi-rapid/drop-token
