apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allowlist-between-services
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
