apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    # NOTE: Update to latest from argo-helm releases
    targetRevision: 0.11.0
    helm:
      values: |
        config:
          logLevel: info
          registries:
            - name: ghcr
              api_url: https://ghcr.io
              prefix: ghcr.io
              credentials: pullsecret:argocd/ghcr-pull
          argocd:
            insecure: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
