global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'event_bus'
    metrics_path: /metrics
    static_configs:
      - targets: ['event_bus:8001']

  - job_name: 'agentic_framework'
    metrics_path: /metrics
    static_configs:
      - targets: ['agentic-framework:8000']
