replicaCount: 1
image:
  repository: ghcr.io/dicky1987/cli-multi-rapid
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
