vcs: git
containers: docker
editor: vscode
js_runtime: node
ai_cli: openai  # options: openai | claude
python_quality:
  ruff: true
  mypy: true
  bandit: true
  semgrep: true
precommit: true

# Optional explicit paths (override PATH)
paths:
  git: ""
  gh: ""
  docker: ""
  code: ""
  node: ""
  npx: ""
  openai: ""
  claude: ""
  pre_commit: ""
  ruff: ""
  mypy: ""
  bandit: ""
  semgrep: ""

