name: quality-gates

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  gates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install base dev tools
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit ruff mypy bandit semgrep markdownlint-cli2 yamllint
          # Optional project deps for type checking can be added here:
          pip install -r requirements.txt || true

      - name: Run pre-commit (all files)
        uses: pre-commit/action@v3.0.0

      - name: Run Ruff (lint)
        run: ruff check .

      - name: Run Mypy (types)
        run: mypy || true

      - name: Run Bandit (security)
        run: bandit -c pyproject.toml -r . || true

      - name: Run Semgrep (SAST)
        run: semgrep --error --config p/ci || true

      - name: YAML lint
        run: yamllint . || true

      - name: Markdown lint
        run: markdownlint-cli2 "**/*.md" || true

      - name: Run tests (pytest) if present
        if: ${{ hashFiles('**/tests/**') != '' }}
        run: |
          pip install pytest
          pytest -q

      - name: Build SBOM (Syft) if Dockerfile present
        if: ${{ hashFiles('Dockerfile') != '' }}
        uses: anchore/syft-action@v0.15.9
        with:
          image: "localbuild:latest"
          source: "."
        continue-on-error: true

      - name: Vulnerability Scan (Grype) if SBOM produced
        if: ${{ hashFiles('sbom.spdx.json') != '' }}
        uses: anchore/scan-action@v3
        with:
          sbom: "sbom.spdx.json"
        continue-on-error: true
