name: Enable Auto-Merge for Approved PRs

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-automerge:
    if: >-
      github.event.pull_request.draft == false &&
      (
        contains(github.event.pull_request.labels.*.name, 'automerge') ||
        github.actor == 'dependabot[bot]'
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
