name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  core:
    name: Core tests (Linux, Python 3.11)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-core-${{ hashFiles('**/pyproject.toml', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-core-

      - name: Install core test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio pytest-cov coverage rich pyyaml

      - name: Run core test suite
        env:
          PYTHONPATH: src
        run: |
          pytest -q tests \
            --ignore=tests/benchmarks \
            --ignore=tests/test_websocket_integration.py \
            --ignore=tests/test_enterprise_modules.py \
            --ignore=tests/test_cli_basics_extra.py \
            --cov=src --cov-report=term-missing --cov-fail-under=0

  extended:
    name: Extended tests (best-effort)
    runs-on: ubuntu-latest
    needs: core
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-ext-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-ext-

      - name: Install full requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run full test suite
        env:
          PYTHONPATH: src
        run: |
          pytest -q tests --cov=src --cov-report=term-missing --maxfail=1

