name: compliance-gate
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - run: python scripts/compliance_gate.py
