name: GUI Terminal CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Unit Tests (core)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          PYTHONPATH: src
        run: pytest -q --maxfail=1 --disable-warnings --cov=src

  parity-windows:
    name: GUI Parity (Windows Offscreen)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyQt6
      - name: Parity smoke
        env:
          PYTHONPATH: gui_terminal/src
          QT_QPA_PLATFORM: offscreen
          GUI_PARITY: '1'
        run: |
          pytest -q tests/test_gui_parity_*_optional.py

  parity-ubuntu:
    name: GUI Parity (Ubuntu Offscreen)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyQt6
      - name: Parity smoke (xvfb)
        env:
          PYTHONPATH: gui_terminal/src
          QT_QPA_PLATFORM: offscreen
          GUI_PARITY: '1'
        run: |
          xvfb-run -a pytest -q tests/test_gui_parity_*_optional.py

