name: registry-codegen

on:
  pull_request:
    paths:
      - 'contracts/registries/**'
      - 'scripts/registry_codegen.py'
      - 'packages/apf_common/**'

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install codegen deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run registry codegen
        run: |
          python scripts/registry_codegen.py
      - name: Ensure no diff after codegen
        run: |
          git diff --exit-code || (echo "Generated files not up-to-date. Run codegen." && exit 1)
