name: Roadmap → Milestones & Issues

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run (no writes)"
        required: true
        default: "true"
        type: choice
        options: ["true", "false"]

permissions:
  contents: read
  issues: write

jobs:
  plan-and-create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Dry-run plan
        if: inputs.dry_run == 'true'
        run: |
          python scripts/create_github_issues.py --repo "${{ github.repository }}" --dry-run

      - name: Create milestones and issues
        if: inputs.dry_run == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/create_github_issues.py --repo "${{ github.repository }}" --token "${GITHUB_TOKEN}"
